### ISSUE TITLE
GitHub Actions build with Ubuntu runner failing with 404 on xz-utils

### ISSUE THREAD

**Issue by eerohele** [SublimeText/UnitTesting#203]
Given a GitHub actions job like this:

```yml
linux:
  runs-on: ubuntu-latest
  container: sublimetext/unittesting
  steps:
    - uses: actions/checkout@v2
    - run: sh -e /etc/init.d/xvfb start
    - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
    - run: |
        PATH="$HOME/.local/bin:$PATH"
        sh github.sh bootstrap
        sh github.sh install_package_control
        sh github.sh run_tests
        sh github.sh run_syntax_tests
```

I get this error:

```
Err:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 xz-utils amd64 5.2.4-1ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/xz-utils/xz-utils_5.2.4-1ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
