### ISSUE TITLE
Not uploading coverage reports when there are tests failures/errors

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#77]
Even with failure, the coverage is generated, but after that its results are not uploaded. The repository is: https://github.com/evandrocoan/PackagesManager

It must always load the results because there is nothing wrong with some tests failing. It is well expected that some tests are going to fail, for some time or even for ever, but just because they fail does not mean they should be moved from the application or block something else.
```
----------------------------------------------------------------------
Ran 60 tests in 8.894s
FAILED (failures=19)
Name                                                            Stmts   Miss  Cover
-----------------------------------------------------------------------------------
1_reloader.py                                                      61     33    46%
2_bootstrap.py                                                    268    165    38%
PackagesManager.py                                                 48     21    56%
packages_manager/__init__.py                                        2      0   100%
packages_manager/automatic_upgrader.py                            139     62    55%
packages_manager/bootstrap.py                                      93     67    28%
packages_manager/ca_certs.py                                       97     49    49%
packages_manager/cache.py                                          46     11    76%
packages_manager/clear_directory.py                                55     42    24%
packages_manager/clients/__init__.py                                0      0   100%
packages_manager/clients/bitbucket_client.py                       85      3    96%
packages_manager/clients/client_exception.py                       10      5    50%
packages_manager/clients/github_client.py                         112     11    90%
packages_manager/clients/json_api_client.py                        28      6    79%
packages_manager/clients/readme_client.py                          35      6    83%
packages_manager/cmd.py                                           138    115    17%
packages_manager/commands/__init__.py                              20      0   100%
packages_manager/commands/add_channel_command.py                   25     15    40%
packages_manager/commands/add_repository_command.py                25     15    40%
packages_manager/commands/advanced_install_package_command.py      61     38    38%
packages_manager/commands/create_package_command.py                 5      1    80%
packages_manager/commands/disable_package_command.py               27     17    37%
packages_manager/commands/discover_packages_command.py              4      1    75%
packages_manager/commands/enable_package_command.py                20     11    45%
packages_manager/commands/existing_packages_command.py             33     26    21%
packages_manager/commands/install_local_dependency_command.py      21     13    38%
packages_manager/commands/install_package_command.py               26     14    46%
packages_manager/commands/list_packages_command.py                 76     59    22%
packages_manager/commands/list_unmanaged_packages_command.py       11      6    45%
packages_manager/commands/packages_manager_insert_command.py        5      2    60%
packages_manager/commands/remove_channel_command.py                31     23    26%
packages_manager/commands/remove_package_command.py                41     24    41%
packages_manager/commands/remove_repository_command.py             24     16    33%
packages_manager/commands/satisfy_dependencies_command.py          31     17    45%
packages_manager/commands/upgrade_all_packages_command.py          43     30    30%
packages_manager/commands/upgrade_package_command.py               42     28    33%
packages_manager/console_write.py                                  14      2    86%
packages_manager/deps/__init__.py                                   0      0   100%
packages_manager/deps/asn1crypto/__init__.py                        3      0   100%
packages_manager/deps/asn1crypto/_elliptic_curve.py                90     46    49%
packages_manager/deps/asn1crypto/_errors.py                        12      7    42%
packages_manager/deps/asn1crypto/_ffi.py                           13      3    77%
packages_manager/deps/asn1crypto/_int.py                           54     40    26%
packages_manager/deps/asn1crypto/_iri.py                          140    124    11%
packages_manager/deps/asn1crypto/_ordereddict.py                   91     88     3%
packages_manager/deps/asn1crypto/_teletex_codec.py                 26      7    73%
packages_manager/deps/asn1crypto/_types.py                         23     13    43%
packages_manager/deps/asn1crypto/algos.py                         273    159    42%
packages_manager/deps/asn1crypto/core.py                         1967   1599    19%
packages_manager/deps/asn1crypto/keys.py                          353    234    34%
packages_manager/deps/asn1crypto/parser.py                         98     86    12%
packages_manager/deps/asn1crypto/pem.py                            87     74    15%
packages_manager/deps/asn1crypto/util.py                          287    220    23%
packages_manager/deps/asn1crypto/version.py                         3      0   100%
packages_manager/deps/asn1crypto/x509.py                          939    543    42%
packages_manager/deps/oscrypto/__init__.py                         64     49    23%
packages_manager/deps/oscrypto/_errors.py                          13      7    46%
packages_manager/deps/oscrypto/_linux_bsd/__init__.py               0      0   100%
packages_manager/deps/oscrypto/_linux_bsd/trust_list.py            51     43    16%
packages_manager/deps/oscrypto/_types.py                           20     11    45%
packages_manager/deps/oscrypto/errors.py                           32     10    69%
packages_manager/deps/oscrypto/trust_list.py                      105     80    24%
packages_manager/deps/oscrypto/version.py                           3      0   100%
packages_manager/download_manager.py                              195     73    63%
packages_manager/downloaders/__init__.py                            8      2    75%
packages_manager/downloaders/background_downloader.py              20     14    30%
packages_manager/downloaders/binary_not_found_error.py             10      5    50%
packages_manager/downloaders/caching_downloader.py                 89     19    79%
packages_manager/downloaders/cli_downloader.py                     34     23    32%
packages_manager/downloaders/curl_downloader.py                   164    141    14%
packages_manager/downloaders/decoding_downloader.py                28      9    68%
packages_manager/downloaders/downloader_exception.py               10      5    50%
packages_manager/downloaders/limiting_downloader.py                14      5    64%
packages_manager/downloaders/non_clean_exit_error.py               16      6    62%
packages_manager/downloaders/non_http_error.py                     10      5    50%
packages_manager/downloaders/rate_limit_exception.py                7      4    43%
packages_manager/downloaders/urllib_downloader.py                 143     58    59%
packages_manager/downloaders/wget_downloader.py                   174    148    15%
packages_manager/downloaders/win_downloader_exception.py            3      0   100%
packages_manager/file_not_found_error.py                           10      5    50%
packages_manager/http/__init__.py                                  37     32    14%
packages_manager/http/debuggable_http_connection.py                41      6    85%
packages_manager/http/debuggable_http_handler.py                   19     12    37%
packages_manager/http/debuggable_http_response.py                  39      7    82%
packages_manager/http/debuggable_https_response.py                  3      0   100%
packages_manager/http/invalid_certificate_exception.py             22     13    41%
packages_manager/http/persistent_handler.py                        75     35    53%
packages_manager/http/validating_https_connection.py              217    129    41%
packages_manager/http/validating_https_handler.py                  38     14    63%
packages_manager/http_cache.py                                     36      3    92%
packages_manager/loader.py                                        233    156    33%
packages_manager/open_compat.py                                    26      3    88%
packages_manager/package_cleanup.py                               204    110    46%
packages_manager/package_creator.py                                50     39    22%
packages_manager/package_disabler.py                              153    134    12%
packages_manager/package_installer.py                             108     58    46%
packages_manager/package_io.py                                     75     20    73%
packages_manager/package_manager.py                               946    687    27%
packages_manager/package_renamer.py                                60     30    50%
packages_manager/processes.py                                      54     51     6%
packages_manager/providers/__init__.py                              7      0   100%
packages_manager/providers/bitbucket_repository_provider.py        50     10    80%
packages_manager/providers/channel_provider.py                    145     29    80%
packages_manager/providers/github_repository_provider.py           52     10    81%
packages_manager/providers/github_user_provider.py                 57     12    79%
packages_manager/providers/provider_exception.py                   10      5    50%
packages_manager/providers/release_selector.py                     54      2    96%
packages_manager/providers/repository_provider.py                 434    177    59%
packages_manager/providers/schema_compat.py                        20      1    95%
packages_manager/semver.py                                        263    156    41%
packages_manager/settings.py                                       46      7    85%
packages_manager/show_error.py                                     34     22    35%
packages_manager/show_quick_panel.py                                6      4    33%
packages_manager/sys_path.py                                      108     77    29%
packages_manager/text.py                                           17      0   100%
packages_manager/thread_progress.py                                38     34    11%
packages_manager/unicode.py                                        84     67    20%
packages_manager/upgraders/__init__.py                              0      0   100%
packages_manager/upgraders/git_upgrader.py                         75     63    16%
packages_manager/upgraders/hg_upgrader.py                          49     38    22%
packages_manager/upgraders/vcs_upgrader.py                          7      4    43%
packages_manager/versions.py                                       61      9    85%
-----------------------------------------------------------------------------------
TOTAL                                                           11537   7185    38%
UnitTesting: Done.
The command "sh travis.sh run_tests --coverage" exited with 1.
Done. Your build exited with 1.
```

**Comment by randy3k** [comment]
I believe that it is a common practice not to upload the report upon failures. However, you could modifier your travis/appveyor configuration such that the report is still uploaded even upon failures.

**Comment by evandrocoan** [comment]
Yes, but I do think it is trivial because the upload seems to be done after the https://github.com/SublimeText/UnitTesting/blob/master/sbin/run_tests.py python script finishes.

It seems that `run_tests.py` return a error code when there are errors/failures on the build. This causes the `.travis.yml` build file to halt and not run the `codecov`:
https://github.com/SublimeText/UnitTesting/blob/9b938ee78012299f1b1abdbd1f00f179a362ad3e/.travis.yml#L48-L54

I think I could trick it by forcing the `run_tests.py` always to return a success code, however it should causes the build badge to always report successful.

It seems that `.travis.yml` is cannot report parcial results on its badge, then it should not help too much.

**Comment by randy3k** [comment]
Instead of putting the `codecov` code under `after_success` in `.travis.yml`, it could be placed under `script` so that it still uploads the report no matter what the status of the build is.

**Comment by evandrocoan** [comment]
Thanks, it kinda worked. But I have a hard time trying to edit the `.travis.yml`. This was the one which seemed to work:
```yaml
env:
    global:
        - PACKAGE="PackagesManager" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install python-coveralls;
            pip3 install codecov;
      fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install python-coveralls;
            pip install codecov;
      fi
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests
    - coveralls
    - codecov

after_success:
    # remove the following if `coveralls` is not needed
    - echo

notifications:
    email: false
```

**Comment by evandrocoan** [comment]
I tried the same for AppVeyor, but the script just halted:
```
UnitTesting: Done.
ScriptHalted
```
https://ci.appveyor.com/project/evandrocoan/packagesmanager/build/1.0.11

This are the changes:
```yaml
environment:
    # The package name
    PACKAGE: "PackagesManager"
    SUBLIME_TEXT_VERSION : "3"

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    # - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:

    # run tests with test coverage report
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
    - "SET PYTHON=C:\Python33"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install codecov
    - codecov

after_test:
    - echo
```
