### ISSUE TITLE
AppVeyor is using Python 2.7.14 instead of Python 3.3

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#81]
I just do not know how it can use Python 2. I use almost the same `appveyor.yml` you suggest:
```

environment:
    # The package name
    PACKAGE: "WrapPlus"
    SUBLIME_TEXT_VERSION : "3"


install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    - ps: pip install coverage codacy-coverage
    # install Package Control
    # - ps: .\appveyor.ps1 "install_package_control" -verbose


build: off


test_script:
    # run tests with test coverage report
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
    - echo


on_finish:
    - "SET PYTHON=C:\Python33"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install codecov
    - codecov
    - python --version
    - coverage xml -o coverage.xml
    - python-codacy-coverage
```
https://github.com/evandrocoan/WrapPlus/blob/5680b39c0b9eebf44397a83341cb314764b446d0/appveyor.yml

___
After adding that `python --version` we see that the python version is `2.7.14` on the AppVeyor build:
```
...
==> Uploading
    .url https://codecov.io
    .query service=appveyor&package=py2.0.14&job=evandrocoan%2Fwrapplus%2F1.0.22&build=2snio61i77gcab3m&branch=master&commit=5680b39c0b9eebf44397a83341cb314764b446d0&slug=evandrocoan%2FWrapPlus
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/evandrocoan/WrapPlus/commit/5680b39c0b9eebf44397a83341cb314764b446d0
python --version
Python 2.7.14
coverage xml -o coverage.xml
Couldn't parse 'C:\projects\wrapplus\wrap_plus.py' as Python source: 'invalid syntax' at line 987
Command exited with code 1
python-codacy-coverage
2018-01-25 23:51:18,059 - ERROR - Coverage report coverage.xml not found.
Command exited with code 1
```

https://ci.appveyor.com/project/evandrocoan/wrapplus/build/1.0.22
